quarkus.http.port=8080

# SmallRye JWT Settings
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=https://example.com/issuer

# For automated demonstration purposes without managing external certificate keystores,
# we instruct smallrye to expect signed tokens matching our quick sign setup.
smallrye.jwt.sign.key.location=privateKey.pem

# Disable automatic OpenAPI stuff
quarkus.test.continuous-testing=disabled
quarkus.devservices.enabled=false
# Disable automatic OpenAPI security scheme generation entirely
quarkus.smallrye-openapi.auto-add-security-requirements=false

# Prevent Quarkus from automatically adding security roles to OpenAPI roles definitions
quarkus.smallrye-openapi.security-roles-as-security-requirements=false
quarkus.smallrye-openapi.filter=com.example.crud.infrastructure.config.SecuritySchemeFilter

# Configure H2 In-Memory Database
quarkus.datasource.db-kind=h2
quarkus.datasource.username=sa
quarkus.datasource.password=
quarkus.datasource.jdbc.url=jdbc:h2:mem:product_db

# Database generation strategy for dev/testing environment
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true

# Set the default console log level (INFO, DEBUG, or TRACE)
quarkus.log.console.level=DEBUG

# Enable HTTP Request/Response logging (Shows every path hit in real-time)
quarkus.http.access-log.category=io.quarkus.http.access-log
quarkus.http.access-log.enabled=true
quarkus.log.category."io.quarkus.http.access-log".level=INFO

# Turn on Security and JWT Debugging (Crucial for seeing why a token passes or fails)
quarkus.log.category."io.quarkus.security".level=DEBUG
quarkus.log.category."io.smallrye.jwt".level=DEBUG

# RESTEasy Reactive endpoint routing details
quarkus.log.category."io.quarkus.resteasy.reactive".level=DEBUG
